# Generated by Django 3.2 on 2022-08-19 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', validators=[django.core.validators.FileExtensionValidator(['csv'])])),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
