# Generated by Django 3.2 on 2022-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
