# Generated by Django 3.2 on 2022-08-26 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_application', '0002_auto_20220820_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='DashboardCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('data_column', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('len', 'len'), ('sum', 'sum'), ('avg', 'avg')], default='len', max_length=10)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_data', to='dashboard_application.uploadedfile')),
            ],
        ),
    ]
