# Generated by Django 3.2 on 2022-08-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_application', '0003_auto_20220826_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardChartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('data_column', models.CharField(max_length=100)),
                ('group_common_data', models.BooleanField(default=False)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_charts', to='dashboard_application.uploadedfile')),
            ],
        ),
    ]
