# Generated by Django 3.2 on 2022-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_application', '0004_dashboardchartsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardchartsettings',
            name='data_column',
        ),
        migrations.AddField(
            model_name='dashboardchartsettings',
            name='data_x',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dashboardchartsettings',
            name='data_y',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
