# Generated by Django 3.2 on 2022-08-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_application', '0005_auto_20220830_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardchartsettings',
            name='data_x',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dashboardchartsettings',
            name='data_y',
            field=models.CharField(max_length=100),
        ),
    ]
