# Generated by Django 3.2 on 2022-09-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_application', '0010_auto_20220904_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardchartsettings',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Graph'), ('doughnut', 'Doughnut Chart')], default='bar', max_length=20),
        ),
    ]
